cameras_controller:
  ros__parameters:
    # camera_types: ['rgb', 'thm']
    camera_types: ['thm']
    rgb:
      port_or_ip: "/dev/video0"
      fps: 30
      resolution: [1920, 1080, 3]
      restart_seconds_no_frames: 10.0
    thm:
      port_or_ip: "/dev/video0"
      fps: 9
      resolution: [160, 120, 1]
      restart_seconds_no_frames: 10.0