ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    odom0: /odom
    odom0_config: [true,  true,  false,   # x, y, z
                   false, false, true,   # roll, pitch, yaw
                   true,  true,  false,   # vx, vy, vz
                   false, false, true,   # vroll, vpitch, vyaw
                   false, false, false]   # ax, ay, az

    imu0: /imu
    imu0_config: [false, false, false,   # x, y, z (IMUs don't provide pos)
                  false, false, true,    # roll, pitch, yaw (optional, if fused)
                  false, false, false,   # vx, vy, vz
                  true,  true,  true,    # vroll, vpitch, vyaw
                  true,  true,  true]    # ax, ay, az

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
