<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="waverover_gazebo">

  <xacro:include filename="$(find waverover_description)/urdf/util.xacro" />

  <gazebo reference="base_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <gazebo reference="top_shell_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <gazebo reference="accessories_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="accessories1_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="imu_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="oled_screen_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/BlueGlow</material>
  </gazebo>

  <gazebo reference="wheel_back_left_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_front_left_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_front_right_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_back_right_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <namespace></namespace>

      <ros>
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>

      <robot_base_frame>base_footprint</robot_base_frame>
      <odometry_frame>odom</odometry_frame>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

      <update_rate>100.0</update_rate>
      <num_wheel_pairs>2</num_wheel_pairs>
      <left_joint>wheel_front_left_joint</left_joint>
      <right_joint>wheel_front_right_joint</right_joint>
      <left_joint>wheel_back_left_joint</left_joint>
      <right_joint>wheel_back_right_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>

      <torque>2</torque>
      <max_wheel_torque>2</max_wheel_torque>
      <max_wheel_acceleration>2</max_wheel_acceleration>

    </plugin>
  </gazebo>

</robot>
